[build]
base = "site"
publish = "output"

[build.lifecycle]
onInit = "node --version"
onPreBuild = "printenv | tr '\\n' ' '"
onBuild = "pwd"

[build.environment]
TEST_ENVIRONMENT_VARIABLE = "ECHO_THIS"