[build]
publish = "/output"
functions = "/functions"
command = "echo $(pwd) && mkdir -p output && cp index.html output/index.html"

[build.lifecycle]
onBuild = "echo $(pwd) && mkdir -p output && cp index.html output/index.html"
onPostBuild = "printenv | grep TEST_ENVIRONMENT_VARIABLE | tr '\n' ' '"

[build.environment]
TEST_ENVIRONMENT_VARIABLE = "ECHO_THIS"
ZISI_VERSION = "0.4.0-9"