[build]
publish = "/output"
functions = "/functions"
command = "echo $(pwd) && mkdir -p output && cp index.html output/index.html && ls $NVM_DIR/versions/node && echo \"SOCKET: $(file /tmp/netlify-buildbot-socket)\""

[build.environment]
TEST_ENVIRONMENT_VARIABLE = "ECHO_THIS"
ZISI_VERSION = "0.4.0-9"