[build]
publish = "output"

[build.lifecycle]
onBuild = "mkdir -p output && cp index.html output/index.html"
onPostBuild = "printenv | tr '\n' ' '"
onInvalid = "invalid build command"

[build.environment]
TEST_ENVIRONMENT_VARIABLE = "ECHO_THIS"