[build]
publish = "/output"

[build.lifecycle]
onBuild = "echo $(pwd) && mkdir -p output && cp index.html output/index.html"
onPostBuild = "printenv | grep TEST_ENVIRONMENT_VARIABLE | tr '\n' ' '"

[build.environment]
TEST_ENVIRONMENT_VARIABLE = "ECHO_THIS"